-- Transcription du schéma « Visual Studio Dark » de Rider (rider-theme-pack).
-- Les valeurs proviennent de colorSchemes/VisualStudioDark.xml, pas d'un relevé à l'œil.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "vsdark"

local c = {
  fond                = "#1e1e1e",
  fond_flottant       = "#2b2d30",
  fond_ligne_active   = "#0f0f0f",
  fond_selection      = "#245b82",
  fond_recherche      = "#653305",
  fond_occurrence     = "#406f11",
  fond_paire          = "#0e4583",
  fond_gabarit        = "#232525",
  fond_separateur     = "#212121",

  texte               = "#dcdcdc",
  texte_attenue       = "#8b999f",
  numero_ligne        = "#8a8a8a",
  numero_ligne_active = "#e0e0e0",
  guide_indentation   = "#464646",
  guide_selectionne   = "#505050",
  separateur          = "#4d4d4d",
  espaces             = "#606060",
  replie              = "#a9a9a9",
  inutilise           = "#a9a9a9",

  mot_cle             = "#569cd6",
  mot_cle_controle    = "#d8a0df",
  chaine              = "#d69d85",
  echappement         = "#e07a00",
  nombre              = "#b5cea8",
  commentaire         = "#57a64a",
  type                = "#4ec9b0",
  interface           = "#b8d7a3",
  methode             = "#dcdca9",
  methode_extension   = "#d8d9a8",
  parametre           = "#9cdcfe",
  attribut            = "#bbb529",
  razor               = "#a699e6",
  gabarit_route       = "#62ccff",
  lien                = "#287bde",
  todo                = "#87cefa",

  erreur              = "#ff3333",
  avertissement       = "#ffb700",
  information         = "#aeae80",

  vcs_ajoute          = "#384c38",
  vcs_modifie         = "#374752",
  vcs_supprime        = "#656e76",
  diff_ajoute         = "#294436",
  diff_supprime       = "#484a4a",
  diff_modifie        = "#385570",
  diff_conflit        = "#45302b",

  point_arret         = "#3a2323",
  point_execution     = "#665001",

  rouge               = "#d62525",
  vert                = "#00a800",
  jaune               = "#b58b00",
  bleu                = "#2683bd",
  magenta             = "#aa3aaa",
  cyan                = "#009696",
  gris                = "#999999",
  gris_fonce          = "#666666",
}

local groupes = {
  Normal            = { fg = c.texte, bg = c.fond },
  NormalNC          = { fg = c.texte, bg = c.fond },
  NormalFloat       = { fg = c.texte, bg = c.fond_flottant },
  FloatBorder       = { fg = c.separateur, bg = c.fond_flottant },
  FloatTitle        = { fg = c.texte, bg = c.fond_flottant, bold = true },
  Cursor            = { fg = c.fond, bg = "#bbbbbb" },
  TermCursor        = { fg = c.fond, bg = "#bbbbbb" },
  CursorLine        = { bg = c.fond_ligne_active },
  CursorColumn      = { bg = c.fond_ligne_active },
  ColorColumn       = { bg = c.fond_ligne_active },
  LineNr            = { fg = c.numero_ligne, bg = c.fond },
  CursorLineNr      = { fg = c.numero_ligne_active, bg = c.fond_ligne_active },
  SignColumn        = { bg = c.fond },
  FoldColumn        = { fg = c.numero_ligne, bg = c.fond },
  Folded            = { fg = c.replie, bg = c.fond_ligne_active },
  Visual            = { bg = c.fond_selection },
  VisualNOS         = { bg = c.fond_selection },
  Search            = { bg = c.fond_recherche },
  IncSearch         = { bg = c.fond_recherche, bold = true },
  CurSearch         = { bg = c.fond_occurrence },
  MatchParen        = { bg = c.fond_paire, bold = true },
  NonText           = { fg = c.espaces },
  Whitespace        = { fg = c.espaces },
  SpecialKey        = { fg = c.espaces },
  Conceal           = { fg = c.texte_attenue },
  Directory         = { fg = c.mot_cle },
  Title             = { fg = c.texte, bold = true },
  Question          = { fg = c.mot_cle },
  MoreMsg           = { fg = c.commentaire },
  ModeMsg           = { fg = c.texte, bold = true },
  ErrorMsg          = { fg = c.erreur },
  WarningMsg        = { fg = c.avertissement },
  Error             = { fg = c.erreur },
  Todo              = { fg = c.todo, bold = true },
  Underlined        = { fg = c.lien, underline = true },
  Ignore            = { fg = c.texte_attenue },

  StatusLine        = { fg = c.texte, bg = c.fond_flottant },
  StatusLineNC      = { fg = c.texte_attenue, bg = c.fond_separateur },
  WinBar            = { fg = c.texte, bg = c.fond },
  WinBarNC          = { fg = c.texte_attenue, bg = c.fond },
  WinSeparator      = { fg = c.separateur, bg = c.fond },
  VertSplit         = { fg = c.separateur, bg = c.fond },
  TabLine           = { fg = c.texte_attenue, bg = c.fond_separateur },
  TabLineSel        = { fg = c.texte, bg = c.fond },
  TabLineFill       = { bg = c.fond_separateur },
  QuickFixLine      = { bg = c.fond_selection },

  Pmenu             = { fg = c.texte, bg = c.fond_flottant },
  PmenuSel          = { fg = c.texte, bg = c.fond_selection },
  PmenuSbar         = { bg = c.fond_flottant },
  PmenuThumb        = { bg = c.separateur },

  Comment           = { fg = c.commentaire },
  SpecialComment    = { fg = c.commentaire },
  Constant          = { fg = c.nombre },
  String            = { fg = c.chaine },
  Character         = { fg = c.chaine },
  Number            = { fg = c.nombre },
  Float             = { fg = c.nombre },
  Boolean           = { fg = c.mot_cle },
  Identifier        = { fg = c.texte },
  Function          = { fg = c.methode },
  Statement         = { fg = c.mot_cle },
  Conditional       = { fg = c.mot_cle_controle },
  Repeat            = { fg = c.mot_cle_controle },
  Label             = { fg = c.mot_cle_controle },
  Exception         = { fg = c.mot_cle_controle },
  Operator          = { fg = c.texte },
  Keyword           = { fg = c.mot_cle },
  PreProc           = { fg = c.mot_cle_controle },
  Include           = { fg = c.mot_cle },
  Define            = { fg = c.mot_cle_controle },
  Macro             = { fg = c.mot_cle_controle },
  PreCondit         = { fg = c.mot_cle_controle },
  Type              = { fg = c.type },
  StorageClass      = { fg = c.mot_cle },
  Structure         = { fg = c.type },
  Typedef           = { fg = c.type },
  Special           = { fg = c.echappement },
  SpecialChar       = { fg = c.echappement },
  Tag               = { fg = c.mot_cle },
  Delimiter         = { fg = c.texte },
  Debug             = { fg = c.attribut },

  DiagnosticError            = { fg = c.erreur },
  DiagnosticWarn             = { fg = c.avertissement },
  DiagnosticInfo             = { fg = c.information },
  DiagnosticHint             = { fg = c.texte_attenue },
  DiagnosticOk               = { fg = c.commentaire },
  DiagnosticUnderlineError   = { undercurl = true, sp = c.erreur },
  DiagnosticUnderlineWarn    = { undercurl = true, sp = c.avertissement },
  DiagnosticUnderlineInfo    = { undercurl = true, sp = c.information },
  DiagnosticUnderlineHint    = { undercurl = true, sp = c.texte_attenue },
  DiagnosticVirtualTextError = { fg = c.erreur },
  DiagnosticVirtualTextWarn  = { fg = c.avertissement },
  DiagnosticVirtualTextInfo  = { fg = c.information },
  DiagnosticVirtualTextHint  = { fg = c.texte_attenue },
  DiagnosticDeprecated       = { strikethrough = true, sp = c.replie },
  DiagnosticUnnecessary      = { fg = c.inutilise },

  DiffAdd           = { bg = c.diff_ajoute },
  DiffChange        = { bg = c.diff_modifie },
  DiffDelete        = { bg = c.diff_supprime },
  DiffText          = { bg = c.fond_selection },
  diffAdded         = { fg = c.commentaire },
  diffRemoved       = { fg = c.rouge },
  diffChanged       = { fg = c.mot_cle },
  Added             = { fg = c.commentaire },
  Removed           = { fg = c.rouge },
  Changed           = { fg = c.mot_cle },
  GitSignsAdd       = { fg = c.commentaire },
  GitSignsChange    = { fg = c.mot_cle },
  GitSignsDelete    = { fg = c.rouge },

  ["@comment"]                    = { fg = c.commentaire },
  ["@comment.todo"]               = { fg = c.todo, bold = true },
  ["@comment.note"]               = { fg = c.todo, bold = true },
  ["@comment.warning"]            = { fg = c.avertissement, bold = true },
  ["@comment.error"]              = { fg = c.erreur, bold = true },
  ["@string"]                     = { fg = c.chaine },
  ["@string.escape"]              = { fg = c.echappement },
  ["@string.special"]             = { fg = c.echappement },
  ["@string.regexp"]              = { fg = c.echappement },
  ["@character"]                  = { fg = c.chaine },
  ["@character.special"]          = { fg = c.echappement },
  ["@number"]                     = { fg = c.nombre },
  ["@number.float"]               = { fg = c.nombre },
  ["@boolean"]                    = { fg = c.mot_cle },
  ["@constant"]                   = { fg = c.texte },
  ["@constant.builtin"]           = { fg = c.mot_cle },
  ["@constant.macro"]             = { fg = c.mot_cle_controle },
  ["@keyword"]                    = { fg = c.mot_cle },
  ["@keyword.function"]           = { fg = c.mot_cle },
  ["@keyword.operator"]           = { fg = c.mot_cle },
  ["@keyword.import"]             = { fg = c.mot_cle },
  ["@keyword.type"]               = { fg = c.mot_cle },
  ["@keyword.modifier"]           = { fg = c.mot_cle },
  ["@keyword.conditional"]        = { fg = c.mot_cle_controle },
  ["@keyword.repeat"]             = { fg = c.mot_cle_controle },
  ["@keyword.return"]             = { fg = c.mot_cle_controle },
  ["@keyword.exception"]          = { fg = c.mot_cle_controle },
  ["@keyword.coroutine"]          = { fg = c.mot_cle_controle },
  ["@keyword.directive"]          = { fg = c.mot_cle_controle },
  ["@function"]                   = { fg = c.methode },
  ["@function.call"]              = { fg = c.methode },
  ["@function.method"]            = { fg = c.methode },
  ["@function.method.call"]       = { fg = c.methode },
  ["@function.builtin"]           = { fg = c.methode },
  ["@function.macro"]             = { fg = c.mot_cle_controle },
  ["@constructor"]                = { fg = c.type },
  ["@type"]                       = { fg = c.type },
  ["@type.builtin"]               = { fg = c.mot_cle },
  ["@type.definition"]            = { fg = c.type },
  ["@attribute"]                  = { fg = c.attribut },
  ["@attribute.builtin"]          = { fg = c.attribut },
  ["@variable"]                   = { fg = c.texte },
  ["@variable.builtin"]           = { fg = c.mot_cle },
  ["@variable.parameter"]         = { fg = c.parametre },
  ["@variable.member"]            = { fg = c.texte },
  ["@property"]                   = { fg = c.texte },
  ["@field"]                      = { fg = c.texte },
  ["@module"]                     = { fg = c.texte },
  ["@namespace"]                  = { fg = c.texte },
  ["@label"]                      = { fg = c.mot_cle_controle },
  ["@operator"]                   = { fg = c.texte },
  ["@punctuation.delimiter"]      = { fg = c.texte },
  ["@punctuation.bracket"]        = { fg = c.texte },
  ["@punctuation.special"]        = { fg = c.echappement },
  ["@tag"]                        = { fg = c.mot_cle },
  ["@tag.builtin"]                = { fg = c.mot_cle },
  ["@tag.attribute"]              = { fg = c.parametre },
  ["@tag.delimiter"]              = { fg = c.texte },
  ["@markup.heading"]             = { fg = c.mot_cle, bold = true },
  ["@markup.strong"]              = { bold = true },
  ["@markup.italic"]              = { italic = true },
  ["@markup.strikethrough"]       = { strikethrough = true },
  ["@markup.link"]                = { fg = c.lien, underline = true },
  ["@markup.link.url"]            = { fg = c.lien, underline = true },
  ["@markup.raw"]                 = { fg = c.chaine },
  ["@markup.list"]                = { fg = c.mot_cle_controle },
  ["@markup.quote"]               = { fg = c.commentaire, italic = true },
  ["@diff.plus"]                  = { fg = c.commentaire },
  ["@diff.minus"]                 = { fg = c.rouge },
  ["@diff.delta"]                 = { fg = c.mot_cle },

  ["@lsp.type.class"]             = { fg = c.type },
  ["@lsp.type.struct"]            = { fg = c.type },
  ["@lsp.type.enum"]              = { fg = c.interface },
  ["@lsp.type.enumMember"]        = { fg = c.interface },
  ["@lsp.type.interface"]         = { fg = c.interface },
  ["@lsp.type.typeParameter"]     = { fg = c.interface },
  ["@lsp.type.namespace"]         = { fg = c.texte },
  ["@lsp.type.method"]            = { fg = c.methode },
  ["@lsp.type.function"]          = { fg = c.methode },
  ["@lsp.type.property"]          = { fg = c.texte },
  ["@lsp.type.field"]             = { fg = c.texte },
  ["@lsp.type.parameter"]         = { fg = c.parametre },
  ["@lsp.type.variable"]          = { fg = c.parametre },
  ["@lsp.type.keyword"]           = { fg = c.mot_cle },
  ["@lsp.type.string"]            = { fg = c.chaine },
  ["@lsp.type.comment"]           = { fg = c.commentaire },
  ["@lsp.type.number"]            = { fg = c.nombre },
  ["@lsp.type.operator"]          = { fg = c.texte },
  ["@lsp.type.decorator"]         = { fg = c.attribut },
  ["@lsp.type.extensionMethod"]   = { fg = c.methode_extension },
  ["@lsp.type.controlKeyword"]    = { fg = c.mot_cle_controle },
  ["@lsp.type.razorTagHelper"]    = { fg = c.mot_cle },
  ["@lsp.type.razorTransition"]   = { fg = c.razor },
  ["@lsp.type.routeParameter"]    = { fg = c.gabarit_route },
  ["@lsp.mod.deprecated"]         = { strikethrough = true },
  ["@lsp.mod.unused"]             = { fg = c.inutilise },

  LspReferenceText                = { bg = c.fond_occurrence },
  LspReferenceRead                = { bg = c.fond_occurrence },
  LspReferenceWrite               = { bg = c.fond_occurrence },
  LspInlayHint                    = { fg = c.texte_attenue, bg = c.fond_ligne_active },
  LspSignatureActiveParameter     = { fg = c.parametre, bold = true },
  LspCodeLens                     = { fg = c.texte_attenue },

  MiniPickNormal        = { fg = c.texte, bg = c.fond_flottant },
  MiniPickBorder        = { fg = c.separateur, bg = c.fond_flottant },
  MiniPickBorderBusy    = { fg = c.avertissement, bg = c.fond_flottant },
  MiniPickBorderText    = { fg = c.texte, bg = c.fond_flottant },
  MiniPickHeader        = { fg = c.mot_cle, bg = c.fond_flottant },
  MiniPickIconDirectory = { fg = c.mot_cle, bg = c.fond_flottant },
  MiniPickIconFile      = { fg = c.texte_attenue, bg = c.fond_flottant },
  MiniPickMatchCurrent  = { bg = c.fond_selection },
  MiniPickMatchMarked   = { bg = c.fond_occurrence },
  MiniPickMatchRanges   = { fg = c.gabarit_route, bold = true },
  MiniPickPreviewLine   = { bg = c.fond_ligne_active },
  MiniPickPreviewRegion = { bg = c.fond_selection },
  MiniPickPrompt        = { fg = c.mot_cle, bg = c.fond_flottant },
  MiniPickPromptCaret   = { fg = c.texte, bg = c.fond_flottant },
  MiniPickPromptPrefix  = { fg = c.mot_cle, bg = c.fond_flottant },

  MiniFilesNormal         = { fg = c.texte, bg = c.fond_flottant },
  MiniFilesBorder         = { fg = c.separateur, bg = c.fond_flottant },
  MiniFilesBorderModified = { fg = c.avertissement, bg = c.fond_flottant },
  MiniFilesCursorLine     = { bg = c.fond_selection },
  MiniFilesDirectory      = { fg = c.mot_cle },
  MiniFilesFile           = { fg = c.texte },
  MiniFilesTitle          = { fg = c.texte_attenue, bg = c.fond_flottant },
  MiniFilesTitleFocused   = { fg = c.texte, bg = c.fond_flottant, bold = true },

  DapBreakpoint          = { fg = c.erreur },
  DapBreakpointCondition = { fg = c.avertissement },
  DapBreakpointRejected  = { fg = c.texte_attenue },
  DapLogPoint            = { fg = c.lien },
  DapStopped             = { bg = c.point_execution },
  DapUINormal            = { fg = c.texte, bg = c.fond },
  DapUIFloatNormal       = { fg = c.texte, bg = c.fond_flottant },
  DapUIFloatBorder       = { fg = c.separateur, bg = c.fond_flottant },
  DapUIVariable          = { fg = c.parametre },
  DapUIValue             = { fg = c.texte },
  DapUIModifiedValue     = { fg = c.avertissement, bold = true },
  DapUIType              = { fg = c.type },
  DapUIScope             = { fg = c.mot_cle },
  DapUIThread            = { fg = c.commentaire },
  DapUIStoppedThread     = { fg = c.mot_cle },
  DapUIFrameName         = { fg = c.texte },
  DapUICurrentFrameName  = { fg = c.methode, bold = true },
  DapUISource            = { fg = c.interface },
  DapUILineNumber        = { fg = c.numero_ligne },
  DapUIBreakpointsPath   = { fg = c.mot_cle },
  DapUIBreakpointsInfo   = { fg = c.commentaire },
  DapUIBreakpointsCurrentLine = { fg = c.methode, bold = true },
  DapUIWatchesEmpty      = { fg = c.texte_attenue },
  DapUIWatchesValue      = { fg = c.texte },
  DapUIWatchesError      = { fg = c.erreur },
  DapUIDecoration        = { fg = c.mot_cle },
  DapUIPlayPause         = { fg = c.commentaire },
  DapUIRestart           = { fg = c.commentaire },
  DapUIStop              = { fg = c.erreur },
  DapUIStepOver          = { fg = c.mot_cle },
  DapUIStepInto          = { fg = c.mot_cle },
  DapUIStepOut           = { fg = c.mot_cle },
  DapUIStepBack          = { fg = c.mot_cle },
  DapUIUnavailable       = { fg = c.texte_attenue },

  CmpItemAbbr           = { fg = c.texte },
  CmpItemAbbrDeprecated = { fg = c.texte_attenue, strikethrough = true },
  CmpItemAbbrMatch      = { fg = c.gabarit_route, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = c.gabarit_route },
  CmpItemMenu           = { fg = c.texte_attenue },
  CmpItemKindKeyword    = { fg = c.mot_cle },
  CmpItemKindVariable   = { fg = c.parametre },
  CmpItemKindField      = { fg = c.texte },
  CmpItemKindProperty   = { fg = c.texte },
  CmpItemKindMethod     = { fg = c.methode },
  CmpItemKindFunction   = { fg = c.methode },
  CmpItemKindClass      = { fg = c.type },
  CmpItemKindStruct     = { fg = c.type },
  CmpItemKindInterface  = { fg = c.interface },
  CmpItemKindEnum       = { fg = c.interface },
  CmpItemKindEnumMember = { fg = c.interface },
  CmpItemKindSnippet    = { fg = c.echappement },
  CmpItemKindText       = { fg = c.chaine },
  CmpItemKindModule     = { fg = c.texte },
}

for nom, definition in pairs(groupes) do
  vim.api.nvim_set_hl(0, nom, definition)
end

vim.g.terminal_color_0  = "#000000"
vim.g.terminal_color_1  = c.rouge
vim.g.terminal_color_2  = c.vert
vim.g.terminal_color_3  = c.jaune
vim.g.terminal_color_4  = c.bleu
vim.g.terminal_color_5  = c.magenta
vim.g.terminal_color_6  = c.cyan
vim.g.terminal_color_7  = c.gris
vim.g.terminal_color_8  = c.gris_fonce
vim.g.terminal_color_9  = c.rouge
vim.g.terminal_color_10 = c.vert
vim.g.terminal_color_11 = c.jaune
vim.g.terminal_color_12 = c.bleu
vim.g.terminal_color_13 = c.magenta
vim.g.terminal_color_14 = c.cyan
vim.g.terminal_color_15 = "#ffffff"
